export default [
{
login: "edenbarhum",
id: 20094244,
node_id: "MDQ6VXNlcjIwMDk0MjQ0",
avatar_url: "https://avatars1.githubusercontent.com/u/20094244?v=4",
gravatar_id: "",
url: "https://api.github.com/users/edenbarhum",
html_url: "https://github.com/edenbarhum",
followers_url: "https://api.github.com/users/edenbarhum/followers",
following_url: "https://api.github.com/users/edenbarhum/following{/other_user}",
gists_url: "https://api.github.com/users/edenbarhum/gists{/gist_id}",
starred_url: "https://api.github.com/users/edenbarhum/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/edenbarhum/subscriptions",
organizations_url: "https://api.github.com/users/edenbarhum/orgs",
repos_url: "https://api.github.com/users/edenbarhum/repos",
events_url: "https://api.github.com/users/edenbarhum/events{/privacy}",
received_events_url: "https://api.github.com/users/edenbarhum/received_events",
type: "User",
site_admin: false
},
{
login: "asafeliasim",
id: 44918682,
node_id: "MDQ6VXNlcjQ0OTE4Njgy",
avatar_url: "https://avatars2.githubusercontent.com/u/44918682?v=4",
gravatar_id: "",
url: "https://api.github.com/users/asafeliasim",
html_url: "https://github.com/asafeliasim",
followers_url: "https://api.github.com/users/asafeliasim/followers",
following_url: "https://api.github.com/users/asafeliasim/following{/other_user}",
gists_url: "https://api.github.com/users/asafeliasim/gists{/gist_id}",
starred_url: "https://api.github.com/users/asafeliasim/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/asafeliasim/subscriptions",
organizations_url: "https://api.github.com/users/asafeliasim/orgs",
repos_url: "https://api.github.com/users/asafeliasim/repos",
events_url: "https://api.github.com/users/asafeliasim/events{/privacy}",
received_events_url: "https://api.github.com/users/asafeliasim/received_events",
type: "User",
site_admin: false
},
{
login: "yariv245",
id: 6500992,
node_id: "MDQ6VXNlcjY1MDA5OTI=",
avatar_url: "https://avatars3.githubusercontent.com/u/6500992?v=4",
gravatar_id: "",
url: "https://api.github.com/users/yariv245",
html_url: "https://github.com/yariv245",
followers_url: "https://api.github.com/users/yariv245/followers",
following_url: "https://api.github.com/users/yariv245/following{/other_user}",
gists_url: "https://api.github.com/users/yariv245/gists{/gist_id}",
starred_url: "https://api.github.com/users/yariv245/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/yariv245/subscriptions",
organizations_url: "https://api.github.com/users/yariv245/orgs",
repos_url: "https://api.github.com/users/yariv245/repos",
events_url: "https://api.github.com/users/yariv245/events{/privacy}",
received_events_url: "https://api.github.com/users/yariv245/received_events",
type: "User",
site_admin: false
},
{
login: "Legendree",
id: 10800574,
node_id: "MDQ6VXNlcjEwODAwNTc0",
avatar_url: "https://avatars0.githubusercontent.com/u/10800574?v=4",
gravatar_id: "",
url: "https://api.github.com/users/Legendree",
html_url: "https://github.com/Legendree",
followers_url: "https://api.github.com/users/Legendree/followers",
following_url: "https://api.github.com/users/Legendree/following{/other_user}",
gists_url: "https://api.github.com/users/Legendree/gists{/gist_id}",
starred_url: "https://api.github.com/users/Legendree/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/Legendree/subscriptions",
organizations_url: "https://api.github.com/users/Legendree/orgs",
repos_url: "https://api.github.com/users/Legendree/repos",
events_url: "https://api.github.com/users/Legendree/events{/privacy}",
received_events_url: "https://api.github.com/users/Legendree/received_events",
type: "User",
site_admin: false
},
{
login: "amitshabo",
id: 51865606,
node_id: "MDQ6VXNlcjUxODY1NjA2",
avatar_url: "https://avatars0.githubusercontent.com/u/51865606?v=4",
gravatar_id: "",
url: "https://api.github.com/users/amitshabo",
html_url: "https://github.com/amitshabo",
followers_url: "https://api.github.com/users/amitshabo/followers",
following_url: "https://api.github.com/users/amitshabo/following{/other_user}",
gists_url: "https://api.github.com/users/amitshabo/gists{/gist_id}",
starred_url: "https://api.github.com/users/amitshabo/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/amitshabo/subscriptions",
organizations_url: "https://api.github.com/users/amitshabo/orgs",
repos_url: "https://api.github.com/users/amitshabo/repos",
events_url: "https://api.github.com/users/amitshabo/events{/privacy}",
received_events_url: "https://api.github.com/users/amitshabo/received_events",
type: "User",
site_admin: false
},
{
login: "RomSanitovsky",
id: 66727898,
node_id: "MDQ6VXNlcjY2NzI3ODk4",
avatar_url: "https://avatars3.githubusercontent.com/u/66727898?v=4",
gravatar_id: "",
url: "https://api.github.com/users/RomSanitovsky",
html_url: "https://github.com/RomSanitovsky",
followers_url: "https://api.github.com/users/RomSanitovsky/followers",
following_url: "https://api.github.com/users/RomSanitovsky/following{/other_user}",
gists_url: "https://api.github.com/users/RomSanitovsky/gists{/gist_id}",
starred_url: "https://api.github.com/users/RomSanitovsky/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/RomSanitovsky/subscriptions",
organizations_url: "https://api.github.com/users/RomSanitovsky/orgs",
repos_url: "https://api.github.com/users/RomSanitovsky/repos",
events_url: "https://api.github.com/users/RomSanitovsky/events{/privacy}",
received_events_url: "https://api.github.com/users/RomSanitovsky/received_events",
type: "User",
site_admin: false
}
];
