export default {
 
    login: "yarinTag",
    id: 65770513,
    node_id: "MDQ6VXNlcjY1NzcwNTEz",
    avatar_url: "https://avatars0.githubusercontent.com/u/65770513?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/yarinTag",
    html_url: "https://github.com/yarinTag",
    followers_url: "https://api.github.com/users/yarinTag/followers",
    following_url: "https://api.github.com/users/yarinTag/following{/other_user}",
    gists_url: "https://api.github.com/users/yarinTag/gists{/gist_id}",
    starred_url: "https://api.github.com/users/yarinTag/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/yarinTag/subscriptions",
    organizations_url: "https://api.github.com/users/yarinTag/orgs",
    repos_url: "https://api.github.com/users/yarinTag/repos",
    events_url: "https://api.github.com/users/yarinTag/events{/privacy}",
    received_events_url: "https://api.github.com/users/yarinTag/received_events",
    type: "User",
    site_admin: false,
    name: null,
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 3,
    public_gists: 0,
    followers: 1,
    following: 0,
    created_at: "2020-05-22T12:48:25Z",
    updated_at: "2020-11-01T11:13:55Z"

};
